// <auto-generated />
using System;
using DirectoryViewer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectoryViewer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231115135007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("DirectoryViewer.Models.DirectoryModel", b =>
                {
                    b.Property<int>("DirectoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DirectoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("DirectoryViewer.Models.DirectoryModel", b =>
                {
                    b.HasOne("DirectoryViewer.Models.DirectoryModel", "ParentDirectory")
                        .WithMany("ChildDirectories")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("DirectoryViewer.Models.DirectoryModel", b =>
                {
                    b.Navigation("ChildDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
